gl_name_0: db "glCreateShader",0
gl_name_1: db "glShaderSource",0
gl_name_2: db "glCompileShader",0
gl_name_3: db "glGetShaderiv",0
gl_name_4: db "glGetShaderInfoLog",0
gl_name_5: db "glDeleteShader",0
gl_name_6: db "glCreateProgram",0
gl_name_7: db "glAttachShader",0
gl_name_8: db "glLinkProgram",0
gl_name_9: db "glGetProgramiv",0
gl_name_10: db "glGetProgramInfoLog",0
gl_name_11: db "glDeleteProgram",0
gl_name_12: db "glGenVertexArrays",0
gl_name_13: db "glBindVertexArray",0
gl_name_14: db "glDeleteVertexArrays",0
gl_name_15: db "glGenBuffers",0
gl_name_16: db "glBindBuffer",0
gl_name_17: db "glBufferData",0
gl_name_18: db "glDeleteBuffers",0
gl_name_19: db "glVertexAttribPointer",0
gl_name_20: db "glEnableVertexAttribArray",0
gl_name_21: db "glUseProgram",0
gl_name_22: db "glDrawArrays",0
gl_name_23: db "glEnable",0
gl_name_24: db "glGetError",0
gl_name_25: db "glGetUniformLocation",0
gl_name_26: db "glUniform3fv",0
gl_name_27: db "glUniform2fv",0
gl_name_28: db "glGenTextures",0
gl_name_29: db "glBindTexture",0
gl_name_30: db "glTexImage2D",0
gl_name_31: db "glTexParameteri",0
gl_name_32: db "glDeleteTextures",0
gl_name_33: db "glActiveTexture",0
gl_name_34: db "glUniform1i",0
gl_name_35: db "glUniform4fv",0
gl_name_36: db "glDisable",0
align 4
gl_names:
dd gl_name_0-gl_names
dd gl_name_1-gl_names
dd gl_name_2-gl_names
dd gl_name_3-gl_names
dd gl_name_4-gl_names
dd gl_name_5-gl_names
dd gl_name_6-gl_names
dd gl_name_7-gl_names
dd gl_name_8-gl_names
dd gl_name_9-gl_names
dd gl_name_10-gl_names
dd gl_name_11-gl_names
dd gl_name_12-gl_names
dd gl_name_13-gl_names
dd gl_name_14-gl_names
dd gl_name_15-gl_names
dd gl_name_16-gl_names
dd gl_name_17-gl_names
dd gl_name_18-gl_names
dd gl_name_19-gl_names
dd gl_name_20-gl_names
dd gl_name_21-gl_names
dd gl_name_22-gl_names
dd gl_name_23-gl_names
dd gl_name_24-gl_names
dd gl_name_25-gl_names
dd gl_name_26-gl_names
dd gl_name_27-gl_names
dd gl_name_28-gl_names
dd gl_name_29-gl_names
dd gl_name_30-gl_names
dd gl_name_31-gl_names
dd gl_name_32-gl_names
dd gl_name_33-gl_names
dd gl_name_34-gl_names
dd gl_name_35-gl_names
dd gl_name_36-gl_names
